project_name: maze3d
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    binary: maze3d
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  prerelease: auto
brews:
  - name: maze3d
    repository:
      owner: yoshihicode
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/yoshihicode/maze3d"
    description: "Maze 3D is a terminal-based 3D maze game written in Go."
    license: "MIT"
    test: |
      system "#{bin}/maze3d --help"
    install: |
      bin.install "maze3d"
